@startuml Update One Reservations (PUT)

header Massage Reservation Sequence Diagram
footer Page %page% of %lastpage%
title "Update One Reservations (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<service>>\n:jwt" as jwtAuth
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:reservations" as ReservationsDatabase
database "<<MongoDB>>\n:users" as UsersDatabase

client->server ++:req.put('/reservations/:id')
server->routerReservations ++:app.use('/reservations/:id', reservations)

routerReservations--> middlewareAuth ++:protect()
middlewareAuth --> jwtAuth ++:verify(token, secret)
middlewareAuth <-- jwtAuth --:decoded
middlewareAuth --> modelUser ++:findById(decoded.id)
modelUser --> UsersDatabase ++: find({_id:decoded.id})
modelUser <-- UsersDatabase --:user
middlewareAuth <-- modelUser --:req.user
routerReservations <-- middlewareAuth --:next()
routerReservations --> middlewareAuth ++:authorize("admin", "user")
routerReservations <-- middlewareAuth --:next()

routerReservations --> controllersReservations ++:updateReservation()
controllersReservations --> modelReservation ++:findById(req.params.id)
modelReservation --> ReservationsDatabase ++:findById(req.params.id)
modelReservation <-- ReservationsDatabase --:Reservation
controllersReservations <-- modelReservation --:Reservation

alt User is not admin and is not owner of the reservation
    client <-- controllersReservations :response
else Otherwise
    controllersReservations --> modelReservation ++:findByIdAndUpdate(req.params.id, req.body, options)
    modelReservation --> ReservationsDatabase ++:findByIdAndUpdate(req.params.id, req.body, options)
    modelReservation <-- ReservationsDatabase --:Reservation
    controllersReservations <-- modelReservation --:Reservation
    client <-- controllersReservations --:response
    end